# Generated by Django 4.2.30 on 2026-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antibiotic',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
